### ISSUE TITLE
Provide example for using class functions

### ISSUE THREAD

**Issue by Keeo** [vit-vit/CTPL#1]
Hi,
can you provide example how to use threadpool to call member function?

**Comment by Keeo** [comment]
It can be done combination of these two exapmles.
```c++
p.push(third, "additional_param"); 
p.push( [] (int id){ std::cout << "hello from " << id << '\n'; });

//Like this:
struct Hello
{
    void print(int id) {std::cout<<"Hello from:"<<id<<std::endl;}
}

Hello hello;
p.push([](int id, Hello* hello){ hello->print(id);}, &hello); 
```

**Comment by vit-vit** [comment]
you can pass the pointer to the class in the labda capture clause.

    struct Hello {
        void print(int id);
    };
    
    Hello hello;
    p.push([&hello](int id){ hello.print(id); });
then a different overload of the threadpool push function is used. This overload is better because it does not use std::bind and hence does less copy constructions of parameters.
You can pass also pointer this, if you need to call a member function from another member function.

    p.push([=this](int id){ this->member_function(); });

**Comment by Keeo** [comment]
Thank you, lambda functions are still quite new for me.
